<a href="https://colab.research.google.com/github/OkForager/OkForager/blob/main/working_tensorflow_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import pandas as pd

# Create a list of dictionaries with the features [symptoms] and corresponding label [condition]
data = [
    {"condition": "acne", "symptoms": "blackheads"},
    {"condition": "acne", "symptoms": "whiteheads"},
    {"condition": "acne", "symptoms": "papules"},
    {"condition": "acne", "symptoms": "pustules"},
    {"condition": "acne", "symptoms": "nodules"},

    {'condition': "allergies", "symptoms": "itchy nose"},
    {'condition': "allergies", "symptoms": "itchy eyes"},
    {'condition': "allergies", "symptoms": "swollen eyes"},
    {'condition': "allergies", "symptoms": "congestion"},
    {'condition': "allergies", "symptoms": "runny nose"},

    {"condition": "anxiety", "symptoms": "restlessness"},
    {"condition": "anxiety", "symptoms": "difficulty concentrating"},
    {"condition": "anxiety", "symptoms": "irritability"},
    {"condition": "anxiety", "symptoms": "trembling or shaking"},
    {"condition": "anxiety", "symptoms": "tension"},
    {"condition": "anxiety", "symptoms": "insomnia"},

    {"condition": "appendicitis", "symptoms": "middle abdomen pain"},
    {"condition": "appendicitis", "symptoms": "lower right abdomen pain"},
    {"condition": "appendicitis", "symptoms": "loss of appetite"},
    {"condition": "appendicitis", "symptoms": "fever"},
    {"condition": "appendicitis", "symptoms": "nausea"},

    {"condition": "arthritis", "symptoms": "joint pain"},
    {"condition": "arthritis", "symptoms": "joint tenderness"},
    {"condition": "arthritis", "symptoms": "joint inflammation"},
    {"condition": "arthritis", "symptoms": "painful joints"},
    {"condition": "arthritis", "symptoms": "tender joints"},
    {"condition": "arthritis", "symptoms": "red swollen tender joints"},
    {"condition": "arthritis", "symptoms": "swollen painful hands"},
    {"condition": "arthritis", "symptoms": "swollen tender hands"},
    {"condition": "arthritis", "symptoms": "swollen tender feet"},
    {"condition": "arthritis", "symptoms": "red swollen feet"},
    {"condition": "arthritis", "symptoms": "red swollen tender hands"},
    {"condition": "arthritis", "symptoms": "tender swollen arm"},

    {"condition": "asthma", "symptoms": "wheezing"},
    {"condition": "asthma", "symptoms": "shortness of breath"},
    {"condition": "asthma", "symptoms": "tight chest"},
    {"condition": "asthma", "symptoms": "coughing"},

    {"condition": "atopic eczema", "symptoms": "dry itchy skin"},
    {"condition": "atopic eczema", "symptoms": "dry craked skin"},
    {"condition": "atopic eczema", "symptoms": "dry skin"},
    {"condition": "atopic eczema", "symptoms": "sore craked skin"},
    {"condition": "atopic eczema", "symptoms": "dry sore skin"},
    {"condition": "atopic eczema", "symptoms": "swollen skin"},
    {"condition": "atopic eczema", "symptoms": "raised skin bumps"},
    {"condition": "atopic eczema", "symptoms": "sensitive skin"},
    {"condition": "atopic eczema", "symptoms": "red swollen skin"},

    {"condition": "bronchitis", "symptoms": "sore throat"},
    {"condition": "bronchitis", "symptoms": "headache"},
    {"condition": "bronchitis", "symptoms": "runny nose"},
    {"condition": "bronchitis", "symptoms": "blocked nose"},
    {"condition": "bronchitis", "symptoms": "aches and pains"},
    {"condition": "bronchitis", "symptoms": "tiredness"},

    {"condition": "cervical cancer", "symptoms": "tiredness"},
    {"condition": "cervical cancer", "symptoms": "bone pain"},
    {"condition": "cervical cancer", "symptoms": "blood in your urine"},
    {"condition": "cervical cancer", "symptoms": "constipation"},
    {"condition": "cervical cancer", "symptoms": "unusual bleeding"},
    {"condition": "cervical cancer", "symptoms": "discomfort during sex"},


    {"condition": "chest infection", "symptoms": "wheezing"},
    {"condition": "chest infection", "symptoms": "rapid heartbeat"},
    {"condition": "chest infection", "symptoms": "breathlessness"},
    {"condition": "chest infection", "symptoms": "green phlegm"},
    {"condition": "chest infection", "symptoms": "yellow phlegm"},
    {"condition": "chest infection", "symptoms": "phlegm"},
    {"condition": "chest infection", "symptoms": "coughing up blood"},

    {"condition": "chronic pancreatitis", "symptoms": "nausea"},
    {"condition": "chronic pancreatitis", "symptoms": "loss of appetite"},
    {"condition": "chronic pancreatitis", "symptoms": "jaundice"},
    {"condition": "chronic pancreatitis", "symptoms": "urinating frequently"},
    {"condition": "chronic pancreatitis", "symptoms": "feeling very tired"},
    {"condition": "chronic pancreatitis", "symptoms": "ongoing vomiting"},

    {"condition": "chickenpox", "symptoms": "blistering red skin rash"},
    {"condition": "chickenpox", "symptoms": "skin blisters"},
    {"condition": "chickenpox", "symptoms": "skin rash"},
    {"condition": "chickenpox", "symptoms": "sore skin blistering"},
    {"condition": "chickenpox", "symptoms": "nausea"},
    {"condition": "chickenpox", "symptoms": "feeling sick"},
    {"condition": "chickenpox", "symptoms": "painful muscles"},
    {"condition": "chickenpox", "symptoms": "headache"},
    
    {"condition": "chilblains", "symptoms": "skin swelling"},
    {"condition": "chilblains", "symptoms": "stinging skin sensation"},
    {"condition": "chilblains", "symptoms": "burning skin sensation"},
    {"condition": "chilblains", "symptoms": "red swollen skin"},

    {"condition": "chlamydia", "symptoms": "pain when peeing"},
    {"condition": "chlamydia", "symptoms": "unusual discharge from the vagina"},
    {"condition": "chlamydia", "symptoms": "unusual discharge from the penis"},
    {"condition": "chlamydia", "symptoms": "pain in the testicles"},
    {"condition": "chlamydia", "symptoms": "bleeding after sex"},
    {"condition": "chlamydia", "symptoms": "bleeding between periods"},
    {"condition": "chlamydia", "symptoms": "pain in the lower abdomen"},

    {"condition": "chronic kidney disease", "symptoms": "weight loss"},
    {"condition": "chronic kidney disease", "symptoms": "poor appetite"},
    {"condition": "chronic kidney disease", "symptoms": "swollen ankles"},
    {"condition": "chronic kidney disease", "symptoms": "shortness of breath"},
    {"condition": "chronic kidney disease", "symptoms": "increased need to urinate"},
    {"condition": "chronic kidney disease", "symptoms": "insomnia"},
    {"condition": "chronic kidney disease", "symptoms": "nausea"},
    {"condition": "chronic kidney disease", "symptoms": "erectile dysfunction"},
    
    {"condition": "chronic obstructive pulmonary disease", "symptoms": "breathlessness"},
    {"condition": "chronic obstructive pulmonary disease", "symptoms": "persistent cough"},
    {"condition": "chronic obstructive pulmonary disease", "symptoms": "frequent chest infections"},
    {"condition": "chronic obstructive pulmonary disease", "symptoms": "wheezing"},

    {"condition": "cirrhosis", "symptoms": "weight loss"},
    {"condition": "cirrhosis", "symptoms": "muscle wasting"},
    {"condition": "cirrhosis", "symptoms": "nausea"},
    {"condition": "cirrhosis", "symptoms": "tiny red lines on skin above waist level"},
    {"condition": "cirrhosis", "symptoms": "very itchy skin"},
    {"condition": "cirrhosis", "symptoms": "jaundice"},
    {"condition": "cirrhosis", "symptoms": "frequent nosebleeds"},
    {"condition": "cirrhosis", "symptoms": "bleeding gums"},
    {"condition": "cirrhosis", "symptoms": "shivering attacks"},
    {"condition": "cirrhosis", "symptoms": "swelling in the legs"},
    {"condition": "cirrhosis", "symptoms": "swollen abdomen"},
    {"condition": "cirrhosis", "symptoms": "hair loss"},
    {"condition": "cirrhosis", "symptoms": "pain around the liver area"},

    {"condition": "clostridium difficile", "symptoms": "watery diarrhoea"},
    {"condition": "clostridium difficile", "symptoms": "diarrhoea"},
    {"condition": "clostridium difficile", "symptoms": "painful abdomen cramps"},
    {"condition": "clostridium difficile", "symptoms": "headaches"},
    {"condition": "clostridium difficile", "symptoms": "weight loss"},
    {"condition": "clostridium difficile", "symptoms": "fever"},

    {"condition": "cold", "symptoms": "cough"},
    {"condition": "cold", "symptoms": "runny nose"},
    {"condition": "cold", "symptoms": "congestion"},
    {"condition": "cold", "symptoms": "stuffy nose"},
    {"condition": "cold", "symptoms": "sneezing"},
    {"condition": "cold", "symptoms": "hoarse voice"},
    {"condition": "cold", "symptoms": "loss of taste and smell"},
    {"condition": "cold", "symptoms": "sore throat"},

    {"condition": "cold sore", "symptoms": "dehydration"},
    {"condition": "cold sore", "symptoms": "irritated gums"},
    {"condition": "cold sore", "symptoms": "swollen glands"},
    {"condition": "cold sore", "symptoms": "nausea"},

    {"condition": "congenital heart disease", "symptoms": "fainting"},
    {"condition": "congenital heart disease", "symptoms": "chest pains"},
    {"condition": "congenital heart disease", "symptoms": "breathing problems"},
    {"condition": "congenital heart disease", "symptoms": "fatigue"},
    {"condition": "congenital heart disease", "symptoms": "palpitations"},

    {"condition": "conjunctivitis", "symptoms": "red eye"},
    {"condition": "conjunctivitis", "symptoms": "eye burning sensation"},
    {"condition": "conjunctivitis", "symptoms": "enlarged lymph node"},

    {"condition": "constipation", "symptoms": "feeling bloated"},
    {"condition": "constipation", "symptoms": "feeling sick"},
    {"condition": "constipation", "symptoms": "loss of appetite"},
    {"condition": "constipation", "symptoms": "hard to poo"},
    {"condition": "constipation", "symptoms": "abdomen pain"},
    {"condition": "constipation", "symptoms": "being irritable"},
    {"condition": "constipation", "symptoms": "lack of energy"},
    {"condition": "constipation", "symptoms": "foul smelling wind and stools"},

    {"condition": "cough", "symptoms": "severe cough"},

    {"condition": "crohn's disease", "symptoms": "extreme tiredness"},
    {"condition": "crohn's disease", "symptoms": "cramping"},
    {"condition": "crohn's disease", "symptoms": "weight loss"},
    {"condition": "crohn's disease", "symptoms": "blood and mucus in your faeces"},
    {"condition": "crohn's disease", "symptoms": "bloody poo"},
    {"condition": "crohn's disease", "symptoms": "blood in your faeces"},

    {"condition": "croup", "symptoms": "bark-like cough"},
    {"condition": "croup", "symptoms": "croaky voice"},
    {"condition": "croup", "symptoms": "hoarse voice"},
    {"condition": "croup", "symptoms": "difficulty breathing"},

    {"condition": "cystic fibrosis", "symptoms": "recurring chest infections"},
    {"condition": "cystic fibrosis", "symptoms": "bronchiectasis"},
    {"condition": "cystic fibrosis", "symptoms": "shortness of breath"},
    {"condition": "cystic fibrosis", "symptoms": "jaundice"},
    {"condition": "cystic fibrosis", "symptoms": "problems putting on weight"},
    {"condition": "cystic fibrosis", "symptoms": "nasal polyps"},    
    {"condition": "cystic fibrosis", "symptoms": "leaking of small amounts of urine"},
    {"condition": "cystic fibrosis", "symptoms": "unable to have children"},

    {"condition": "cystitis", "symptoms": "stinging when you pee"},
    {"condition": "cystitis", "symptoms": "painful pee"},
    {"condition": "cystitis", "symptoms": "burning pee sensation"},
    {"condition": "cystitis", "symptoms": "needing to pee more often and urgently than normal"},
    {"condition": "cystitis", "symptoms": "urine that's dark, cloudy or strong-smelling"},
    {"condition": "cystitis", "symptoms": "pain low down in your abdomen"},
    {"condition": "cystitis", "symptoms": "blood in your urine"},

    {"condition": "deep vein thrombosis", "symptoms": "swelling and tenderness in one of your legs"},
    {"condition": "deep vein thrombosis", "symptoms": "warm skin"},
    {"condition": "deep vein thrombosis", "symptoms": "red warm skin"},
    {"condition": "deep vein thrombosis", "symptoms": "cramping pain in leg"},
    {"condition": "deep vein thrombosis", "symptoms": "swollen veins"},
    {"condition": "deep vein thrombosis", "symptoms": "swollen sore veins"},
    {"condition": "deep vein thrombosis", "symptoms": "darkened skin around the painful area"},
    {"condition": "deep vein thrombosis", "symptoms": "swollen leg"},
    {"condition": "deep vein thrombosis", "symptoms": "leg pain"},

    {"condition": "dehydration", "symptoms": "headache"},
    {"condition": "dehydration", "symptoms": "dizziness"},
    {"condition": "dehydration", "symptoms": "light-headedness"},
    {"condition": "dehydration", "symptoms": "tiredness"},
    {"condition": "dehydration", "symptoms": "dry mouth"},
    {"condition": "dehydration", "symptoms": "passing small amounts of urine infrequently"},
    {"condition": "dehydration", "symptoms": "lethargic"},
    {"condition": "dehydration", "symptoms": "not passing urine for eight hours"},
    {"condition": "dehydration", "symptoms": "no pee"},
    {"condition": "dehydration", "symptoms": "no sweat"},

    {"condition": "dementia", "symptoms": "memory loss"},
    {"condition": "dementia", "symptoms": "difficulty speaking"},
    {"condition": "dementia", "symptoms": "wandering"},
    {"condition": "dementia", "symptoms": "repeating questions"},
    {"condition": "dementia", "symptoms": "difficulty handling complex tasks"},
    {"condition": "dementia", "symptoms": "difficulty with planning"},
    {"condition": "dementia", "symptoms": "changes in personality and mood"},
    {"condition": "dementia", "symptoms": "periods of mental confusion"},

    {"condition": "dental abscess", "symptoms": "intense, throbbing pain in the affected tooth or gum"},
    {"condition": "dental abscess", "symptoms": "intense tooth pain"},
    {"condition": "dental abscess", "symptoms": "pain that spreads to your ear"},
    {"condition": "dental abscess", "symptoms": "pain that's worse when lying down"},
    {"condition": "dental abscess", "symptoms": "redness and swelling in your face"},
    {"condition": "dental abscess", "symptoms": "loose tooth"},
    {"condition": "dental abscess", "symptoms": "shiny, red and swollen gums"},
    {"condition": "dental abscess", "symptoms": "sensitivity to hot or cold food and drink"},
    {"condition": "dental abscess", "symptoms": "tooth sensitivity"},


    {"condition": "flu", "symptoms": "fever"},
    {"condition": "flu", "symptoms": "sore throat"},
    {"condition": "flu", "symptoms": "body aches"},
    {"condition": "flu", "symptoms": "vomiting"},

    {'condition': "strep throat", "symptoms": "sore throat"},
    {'condition': "strep throat", "symptoms": "fever"},
    {'condition': "strep throat", "symptoms": "swollen lymph nodes"},
    {'condition': "strep throat", "symptoms": "swollen tonsils"},



]


df =pd.DataFrame(data)
#df



In [ ]:
import tensorflow as tf
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


def custom_accuracy(y_true, y_pred):
  y_pred = tf.cast(y_pred, tf.int32)
  y_true = tf.cast(y_true, tf.int32)
  correct_predictions = tf.equal(y_true, y_pred)
  accuracy = tf.reduce_mean(tf.cast(correct_predictions, tf.float32))
  return accuracy


# Load the text based dataset
df = pd.DataFrame(data)

# Convert the conditions to numerical values
encoder = LabelEncoder()
df['condition'] = encoder.fit_transform(df['condition'])

# Convert the symptoms to numerical values using a tokenizer
symptom_texts = df['symptoms'].tolist()
tokenizer = Tokenizer()
tokenizer.fit_on_texts(symptom_texts)
sequences = tokenizer.texts_to_sequences(symptom_texts)

# Pad the sequences to the same length
padded_sequences = pad_sequences(sequences)

# Split the data into features and labels
X = padded_sequences
y = df['condition'].values

# One-hot encode the labels

y = tf.keras.utils.to_categorical(y)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

# Build a neural network model using Tensorflow
model = tf.keras.Sequential()
model.add(tf.keras.layers.Embedding(input_dim= len(tokenizer.word_index)+ 1, output_dim=32, input_length=X.shape[1]))
model.add(tf.keras.layers.LSTM(128, return_sequences=True))
model.add(tf.keras.layers.LSTM(64))
model.add(tf.keras.layers.Dense(128, activation='relu'))
model.add(tf.keras.layers.Dense(y.shape[1], activation='softmax'))


# Compile the model loss = 

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=[custom_accuracy])
x_val = 'symptoms'
y_val = 'condition'

# Train the model
#history = model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data= (X_test, y_test))
model.fit(X_train, y_train, epochs=50, batch_size=32,validation_data=(X_test, y_test))
# Evaluate the model on the test data

#test_loss, test_acc = model.evaluate(X_test, y_test)
#print(test_loss)
#print(test_acc)

input_shape = model.layers[0].input_shape
print(input_shape)
model.save('health_condition_model.h5')

input_shape.shape

In [35]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

input_text = input("Enter symptoms")
input_sequence = tokenizer.texts_to_sequences([input_text])

padded_input = pad_sequences(input_sequence, maxlen=9)

prediction = model.predict(padded_input)

prediction_index = tf.argmax(prediction).numpy()
predicted_label = y_test[prediction_index]

print(predicted_label)
prediction.shape

Enter symptomsfever


1/1 [==============================] - 1s 811ms/step
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


(1, 34)

In [ ]:
history = model.fit(X_train, y_train, epochs=100, batch_size=32, validation_data= (X_test, y_test))

print(history.history.keys())
import matplotlib.pyplot as plt
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')

plt.legend()
plt.show()


In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

def custom_accuracy(y_true, y_pred):
  y_pred = tf.cast(y_pred, tf.int32)
  y_true = tf.cast(y_true, tf.int32)
  correct_predictions = tf.equal(y_true, y_pred)
  accuracy = tf.reduce_mean(tf.cast(correct_predictions, tf.float32))
  return accuracy

# Load the model
model = tf.keras.models.load_model('health_condition_model.h5')

max_words = 10000

# Load the tokenizer
tokenizer = Tokenizer()



input_text = input("Enter symptoms seperated by commas: ")

input_text = [input_text]

input_sequence = tokenizer.texts_to_sequences(input_text)

# Pad the input sequence
input_padded = pad_sequences(input_sequence, maxlen=9)

output = model.predict(input_padded)
print(output)
